version: '3.9'

services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres_pgadmin_yml
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - pg_admin

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_yml
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - pg_admin

networks:
  pg_admin: